### ISSUE TITLE
Make it portable and self contained!

### ISSUE THREAD

**Issue by beppe9000** [Kilian/fromscratch#30]
On startup it should check if there is a ".fromscratch" folder next to the executable and use it instead of the one in the user profile. This way users will be able to use FromScratch with an USB drive regardless of the host pc.

---

Also consider the possibility of using the exe name to define the folder name.

**Comment by bmoyer240** [comment]
+1

**Comment by Kilian** [comment]
Whilst I like the idea and can see how it's useful, this probably won't happen any time soon. That is because electron (underlying technique) itself is not portable. Also, I'm not sure how well a dotfolder handles on usb sticks. 

Having just the .fromscratch folder portable will still leave configuration folders on your system, so that's not an option and i would want it to leave no trace on a machine. Any ideas? :)

**Comment by beppe9000** [comment]
I think that as long as data+exe stay in the same folder I would not mind some AppData garbage if it is not avoidable. Does electron allows you to do a manual cleanup on exit or it locks\recreates the files?

**Comment by Kilian** [comment]
I asked in the Electron slack channel but it doesn't seem to be the case. I'll keep this open on low-priority
