### ISSUE TITLE
Margin control

### ISSUE THREAD

**Issue by otheroom** [Kilian/fromscratch#44]
The margins seem kind of large and it would be nice if the user had some control over them. I see in other issues (#6) you mentioned that don't want to deal with preferences. If there is an editable file that would be fine with me.

**Comment by Kilian** [comment]
I can see where you're coming from, but I'm hesitant to make it configurable because it means I have to make sure it continues working for all values of margins for all new features (and existing ones such as the searchbar) I add and that doesn't sound fun.

The margins are also used in a couple of different places (and ways) in the style, for example to provide the subtle top and bottom gradients. It would be difficult to get right. I am leaning towards putting this to "wontfix", but I'mopen to any ideas of doing this without increasing the maintenance burden too much.

**Comment by otheroom** [comment]
On a laptop those margins eat up a lot of room. I keep FromScratch open at about 30% screen width on the right so I can bring it up over another window that I want to view at the same time. That really limits the amount of text that can be displayed in FromScratch.

What if you went the responsive route and had two different margin/gradient settings based on the window width? I think the margins look fine when the FromScratch window is larger but would like to see them about half that size when the window is smaller.

**Comment by bentsai** [comment]
I'm happy with the margins as is and agree with the approach that reduces complexity. One of the reasons I like using FromScratch is the lack of configurability.

**Comment by otheroom** [comment]
Responsive CSS code could dynamically adjust the margins based on the window width and not require any configuration settings. I'm all for keeping the app simple but it would be nice if it made more efficient use of space automatically.

**Comment by meyerweb** [comment]
I’ll toss in my vote for margin control in some form.  The laptop issue is one I’ve encountered, and even on my desktop, I wish I could make the window more compact.  Making the margins scale with window height and width would be one solution that doesn’t require configuration settings.  In CSS terms, something like `10vmin` would do nicely, I think.

(I’d also love an exposed CSS file so that power users can theme FS however they like, but I can understand why that would be a major can of worms.)

**Comment by Kilian** [comment]
The horizontal margins now automatically size to the width of the window, resulting in a better use of space automatically. The vertical margins will remain the same, to accommodate the search bar and update bars. I'll be adding this into the next official release.

![fromscratch_001](https://user-images.githubusercontent.com/41970/30772698-5269d060-a061-11e7-9be9-1069e84d8999.png)

**Comment by otheroom** [comment]
Looking forward to this, thanks.
