### ISSUE TITLE
keep the indentation on new line

### ISSUE THREAD

**Issue by taniki** [Kilian/fromscratch#46]
It will be better looking and keep the visual flow of text blocks.

**Comment by Kilian** [comment]
Most text editors that do line-wrapping don't do this. 

Codemirror has code available for it here: view-source:https://codemirror.net/demo/indentwrap.html which I have tried in FromScratch before, but took out because in usage it doesn't work very well wheb you start editing and otherwise interacting with the text, which is the thing I want to make the easiest.

I'm not bringing this into FromScratch because while I agree it looks better, it doesn't work better and that's more important to me.

**Comment by taniki** [comment]
I was speaking from dropbox paper UX point of view that I currently use as a scratchpad. It makes more sense for note taking involving list too.

**Comment by Kilian** [comment]
Ah, right. I thought you meant a long sentence that runs over into the next line, my bad.

FromScratch does already automatically preserve the indentation for newlines, so that use case is covered :)
