### ISSUE TITLE
[Feature Request] Line seperators / task headers?

### ISSUE THREAD

**Issue by husainfazel** [Kilian/fromscratch#53]
Hi, 

It would be nice to have a command shortcut to add in page headers / line based separators as shown below. Can be done manually, but a modifier for the line to turn it into a header would be useful!

Stuff to do in the afternoon
----------------------------

[ ] Send a feature request about line seperators
[ ] Make Coffee
[ ] Walk the Dog

Stuff to do at night
----------------------------
[ ] Sleep

**Comment by Kilian** [comment]
I suggest using indentation for this instead of a dash/line, which means you can also collapse e.g. "stuff to do in the afternoon so you can focus on ...whatever it is you do at night ;) Try it and see if it works for you.

I'm trying very hard to not make FromScratch a markdown editor, there's other tools much better for that!

**Comment by Kilian** [comment]
Closing this issue.
