### ISSUE TITLE
Updating FromScratch to 1.4.0 results in broken icon and error on first start

### ISSUE THREAD

**Issue by nilicule** [Kilian/fromscratch#65]
Error thrown on first start - after a force quit the application will start normally:
![screen shot 2018-07-23 at 10 03 43](https://user-images.githubusercontent.com/47522/43066082-f80e64cc-8e63-11e8-8dff-8139618cf60a.png)

Icon seems broken. Screenshot shows broken icon in Alfred, but Spotlight has the same behaviour:
![screen shot 2018-07-23 at 10 03 52](https://user-images.githubusercontent.com/47522/43066083-f8296db2-8e63-11e8-8638-607fff593aaf.png)

**Comment by Kilian** [comment]
Strange. Which version of macos are you using? I'm still on sierra and it works as expected there. Did you overwrite the existing fromscratch,app?

**Comment by nilicule** [comment]
I'm getting this on 10.13.6, but have a colleague who experienced the same on her 10.13.4 version of macos.

We both chose to overwrite the existing FromScratch app.

**Comment by RhythmScout** [comment]
I'm seeing the same thing on 10.13.6, but the app will not start after the error dialog is shown (must force quit)

**Comment by beaudesigns** [comment]
I am seeing this on 10.13.6 as well. If there's any information or testing you need @Kilian, let me know.

**Comment by meyerweb** [comment]
I’m seeing very similar behavior on MacOS 10.11.6 (El Capitan), except the JS error is thrown every time I launch, not just on the first.  Same or similar icon corruption problem (see top of attached)

![screen shot 2018-07-23 at 11 20 09](https://user-images.githubusercontent.com/939727/43086096-8c183a7a-8e6a-11e8-8caa-b235146b0c1c.png)

**Comment by beaudesigns** [comment]
I just tested and it ran as expected for me through the manual installation and build process. 👍 

To clarify too, I was getting the same issues as @meyerweb (Hi Eric, thank you for your many contributions to the industry over the years), where the error was happening every time.

**Comment by Kilian** [comment]
@beaudesigns  it running with the incorrect icon is as expected, since the development process is actually Electron so that's as expected. Not getting an error is too bad, I hoped that would be consistent.

Regardless, could you check https://github.com/Kilian/fromscratch/releases/download/v1.4.1/FromScratch-1.4.1.dmg ? (@nilicule this is new version 1.4.1 from the one in #64, though it has that fix too). For me this fixes the icon, and I hope that it fixes the JS error on load as well, since in this version the only thing vaguely using Path is not executed on mac (because it doesn't have to)

**Comment by beaudesigns** [comment]
I had found and tested 1.4.1 earlier today, and I was hitting the same issue that I was with 1.4.0. But, I just downloaded 1.4.1 and tested it again after doing the manual build and it's working now.

Is it possible that something is available on systems that have done the manual build process, that isn't making it into the final build? Just grasping at straws with that.

**Comment by Kilian** [comment]
Maybe, though I don't really know what! Someone that still has the error, could they send me a screenshot of the /Users/NAME/.fromscratch/ folder? I did some more tracking down and it might be that there is something 'wrong' with that folder.

**Comment by Kilian** [comment]
Here is a new version of 1.4.1 that outputs the location of the contents file (I now think the error happens when writing the content.txt file). 

https://github.com/Kilian/fromscratch/releases/download/v1.4.1/FromScratch-1.4.1-debug.dmg

If someone could install the DMG, and start FromScratch from a terminal using 
```open /Applications/FromScratch.app/Contents/MacOS/FromScratch``` 

This opens a new terminal window with a printed line 
```This is what the filepath is:  /Users/kilian/.fromscratch/content.txt``` 
I think the last part is wrong for people getting that error, but I need to know how wrong. 

It could also be that this version works, since I attempt to resolve the path first.

**Comment by beaudesigns** [comment]
> This is what the filepath is:  /Users/beauwest/.fromscratch/content.txt

This version works for me as well. But the old 1.4.1 was working too.

**Comment by badcat** [comment]
Running the 1.4.1 debug version under macOS 10.12.6 (Sierra) and still see the intro JS error. The icon is fixed.  Cut / Copy  / Paste keyboard is working, however the text entry into the app is extremely slow for the text to preview.  I tried toggling the theme - same slow.  Not sure if this needs an new issue submitted specific to the slowness.

**Comment by Kilian** [comment]
@badcat what is the output if you run it like I describe in https://github.com/Kilian/fromscratch/issues/65#issuecomment-407191721 ?

**Comment by badcat** [comment]
@Kilian Seems OK, no?  
`This is what the filepath is:  /Users/imacd/.fromscratch/content.txt`

**Comment by nilicule** [comment]
Output is:
```
➜  ~ /Applications/FromScratch.app/Contents/MacOS/FromScratch ; exit;
This is what the filepath is:  /Users/remco/.fromscratch/content.txt
2018-07-24 08:48:05.126 FromScratch[10102:9527555] *** WARNING: Textured window <AtomNSWindow: 0x7fe423f43640> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

**Comment by husainfazel** [comment]
Just adding that I'm also receiving a similar error. Subscribing for a resolution.

![screen shot 2018-07-24 at 19 31 24](https://user-images.githubusercontent.com/418404/43155688-5aebba9e-8f78-11e8-9037-f84e91a57830.png)

**Comment by Kilian** [comment]
Hi everyone,

I have a new debug version available: https://github.com/Kilian/fromscratch/releases/download/v1.4.1/FromScratch-1.4.1-debug2.dmg

**If you test this, please back up your .fromscratch folder first**

**Things to test**:

* you don't get the error
* changes you make are still getting saved

This one is kind of 'the nuclear option' since when the error in the above occurs, the code *ignores it*. I think this will work because I suspect that this error only happens during the application startup due to async weirdness specifically in packaged `.app` files, but it could mean none of your changes get saved.

**Comment by kelp** [comment]
I just updated to 1.4.0 and saw the above errors on start. I've updated to the 1.4.1-debug2 version, and am seeing the same issue. If I backup and rename my $HOME/.fromscratch, then FromScratch will start, and it does save new text.

![screenshot 2018-07-31 09 33 03](https://user-images.githubusercontent.com/11240/43473533-47234f5e-94a5-11e8-993f-c2497a335252.png)
<img width="641" alt="screenshot 2018-07-30 16 47 51" src="https://user-images.githubusercontent.com/11240/43473534-4739787e-94a5-11e8-83df-425ee2c6b867.png">

**Comment by Kilian** [comment]
So Fromscratch now starts without any errors for you?

Could you do a `ls -la` in both folders (old and new .fromscratch folders) and copy the output?

**Comment by kelp** [comment]
Yeah, it now starts without any error. However, if I reinstall it, it will error on first start.

Here is the output you asked for:

![screenshot 2018-07-31 10 13 37](https://user-images.githubusercontent.com/11240/43475415-853763a2-94aa-11e8-9e77-a7d6b30595d8.png)

**Comment by Kilian** [comment]
...I figured it out. 🤕 One of the new command line options we have is `--portable`, with the alias `-p`. For some reason, only on first start of an app from /applications, `,-psn_0_1814971` or similar is appended to the launch command, triggering portable mode, which tries to store files adjacent to the application, which it's not allowed to do, causing the error. 

I'm removing the `-p` alias for now and getting 1.4.1 out for all of you!

**Comment by Kilian** [comment]
Available here: https://github.com/Kilian/fromscratch/releases/tag/v1.4.1

**Comment by husainfazel** [comment]
Yes! That fixes the issue on my Mac. Thought you might like to know that there was this minor issue whilst installing:

![screen shot 2018-07-31 at 23 43 09](https://user-images.githubusercontent.com/418404/43489038-eaf34a1e-951b-11e8-9407-4e847af343d2.png)

and is the new UI supposed to look like this: 

![screen shot 2018-07-31 at 23 45 28](https://user-images.githubusercontent.com/418404/43489043-f11ac73c-951b-11e8-8f71-b88e1dd40c2e.png)

**Comment by Kilian** [comment]
Closing this ticket. If anyone else sees the same weirdness as @husainfazel let me know and i'll open a new ticket :)
